### ISSUE TITLE
3D Lessons?

### ISSUE THREAD

**Issue by MV10** [greggman/vertexshaderart#18]
I've been trying to teach my wife some basics of shader programming, and along with some of the introductory material at the .NET OpenTK website, your tutorial videos were extremely helpful. Being able to see the results real-time as you make changes really clicked with her, like no other tutorial ever has.

I realize they're pretty old and they're time-consuming to plan and publish, but is there any chance you'll ever get around to the 3D videos you said were coming "next time" at the end of your Lesson 05?

Either way, your content is greatly appreciated! Everyone knows about shadertoy, your site deserves just as much exposure in my opinion.

**Comment by greggman** [comment]
Sorry, I don't think I'll be making vertexshaderart videos 😢

I think the shadertoy guy, ig, has some videos:

https://www.youtube.com/channel/UCdmAhiG8HQDlz8uyekw4ENw

Otherwise, stuff I helped on that teach 3D

https://webglfundamentals.org
https://webgpufundamentals.org
https://threejs.org/manual
